# Predict `with` using ML Pipeline

In [1]:
import numpy as np

In [3]:
import pickle
import joblib

# Solution 1: Try using joblib instead of pickle (recommended for scikit-learn models)
try:
    with open('pipe.pkl', 'rb') as file:
        pipe = joblib.load(file)
    print("Model loaded successfully with joblib!")
except Exception as e:
    print(f"Joblib loading failed: {e}")
    
    # Solution 2: Try loading with pickle but handle the version compatibility
    try:
        import sklearn
        print(f"Current scikit-learn version: {sklearn.__version__}")
        
        # Load with pickle and handle potential compatibility issues
        with open('pipe.pkl', 'rb') as file:
            pipe = pickle.load(file)
        print("Model loaded successfully with pickle!")
        
    except ValueError as ve:
        print(f"Version compatibility error: {ve}")
        print("\nSuggested solutions:")
        print("1. Recreate the model with your current scikit-learn version")
        print("2. Downgrade scikit-learn to match the version used to create the pickle")
        print("3. Use joblib.load() instead of pickle.load() for scikit-learn models")
        
    except Exception as e:
        print(f"Other error occurred: {e}")

Joblib loading failed: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
Current scikit-learn version: 1.7.2
Version compatibility error: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', 

/home/peeyush/anaconda3/lib/python3.13/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator SimpleImputer from version 0.23.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/peeyush/anaconda3/lib/python3.13/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator ColumnTransformer from version 0.23.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/peeyush/anaconda3/lib/python3.13/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 0.23.1 when using version 

In [3]:
pipe.predict(test_input2)

NameError: name 'pipe' is not defined

# Predict `without` using ML Pipeline

In [4]:
import pickle
import numpy as np

In [5]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [6]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [7]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [8]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/home/peeyush/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [9]:
test_input_sex

array([[0., 1.]])

In [10]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [11]:
test_input_embarked

array([[0., 0., 1.]])

In [12]:
test_input_age = test_input[:,2].reshape(1,1)

In [13]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [14]:
test_input_transformed.shape

(1, 10)

In [15]:
clf.predict(test_input_transformed)

array([1])